name: Staging | Build and publish Maven site

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  site:
    runs-on: ubuntu-latest

    env:
      jdk-version: '19'
      repo-dir: .

    steps:

      # Set up the JDK and Maven settings.xml
      - name: Set up JDK ${{ env.jdk-version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ env.jdk-version }}

      # Checkout this repository
      - name: Checkout this repository
        uses: actions/checkout@v3
        with:
          path: ${{ env.repo-dir }}

      # Build Maven site
      - name: Maven build
        run: mvn -B package
